### ISSUE TITLE
create_test_video fails if pillow version is greater 4.1

### ISSUE THREAD

**Issue by mprobst-irt** [bbc/dvbcss-synctiming#8]
I tried to set up the tool on Ubuntu 16.04

When generating the test content, without changing the script, it fails Generating the video.

Problem is the version of pillow, which was 4.2, downgrading to 4.1 is a workaround.

See also here
https://github.com/python-pillow/Pillow/issues/2614 

The stacktrace of the error is:

`Generating video images...
Traceback (most recent call last):
  File "./src/generate.py", line 424, in <module>
    for frame in frames:
  File "/home/dvbcss/sync_accurcy_test/dvbcss-synctiming/test_sequence_gen/src/video.py", line 321, in genFrameImages
    w,h = font.getsize(text)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 156, in getsize
    size, offset = self.font.getsize(text, direction, features)
SystemError: error return without exception set
Error during creation of wav/png/metadata. Aborting`

**Comment by hugovk** [comment]
Good news, https://github.com/python-pillow/Pillow/issues/2614 has been fixed in this week's Pillow 4.3.0 release.

`pip install -U pillow` should sort it for you.
